name: CI

on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  python:
    uses: ./.github/workflows/python.yml
    with:
      os: ${{ matrix.targets.os }}
      target: ${{ matrix.targets.target }}
      python-version: ${{ matrix.python-version }}
    name: Python CI (${{ matrix.targets.os }} ${{ matrix.targets.target }})
    strategy:
      fail-fast: false
      matrix:
        targets: [
          {os: ubuntu-20.04, target: x86_64},
          {os: ubuntu-22.04, target: x86_64},
          {os: macos-13, target: x86_64},
          {os: macos-14, target: aarch64}
        ]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

  release:
    needs: python
    uses: ./.github/workflows/pypi_release.yml
    with:
      os: ${{ matrix.targets.os }}
      target: ${{ matrix.targets.target }}
      python-version: ${{ matrix.python-version }}
    name: Release (${{ matrix.targets.os }} ${{ matrix.targets.target }})
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        targets: [
          {os: ubuntu-20.04, target: x86_64},
          {os: macos-13, target: x86_64},
          {os: macos-14, target: aarch64}
        ]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    permissions:
      contents: read
      id-token: write
