name: CI

on: [push]

env:
  PYTHON_SRC: "src"

permissions:
  contents: read
  id-token: write

jobs:
  python:
    name: Python CI (${{ matrix.os }})
    uses: ./.github/workflows/python.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
        target: [x86_64]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    with:
      os: ${{ matrix.os }}
      target: ${{ matrix.target }}
      python-version: ${{ matrix.python-version }}

  release:
    name: Release for Python ${{ matrix.python-version }} (${{ matrix.target }}-$${{ matrix.os }})
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: python
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
        target: [x86_64]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.target }}-wheels

      - name: Publish packages to PyPi
        if: ${{ startsWith(github.ref, 'refs/tags') && endsWith(github.ref, steps.metadata.outputs.PACKAGE_VERSION) }}
        uses: pypa/gh-action-pypi-publish@release/v1