name: CI

on: [push]

env:
  PYTHON_SRC: "src"

permissions:
  contents: read

jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
    uses: ./.github/workflows/python.yml
    name: Python CI (${{ matrix.os }})
    with:
      os: ${{ matrix.os }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: python
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
