name: CI

on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  python:
    uses: ./.github/workflows/python.yml
    with:
      os: ${{ matrix.os }}
      target: ${{ matrix.target }}
      python-version: ${{ matrix.python-version }}
    name: Python CI (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
        target: [x86_64]
        python-version: ['3.8', '3.9', '3.10', '3.11']      

  release:
    needs: python
    uses: ./.github/workflows/pypi_release.yml
    with:
      os: ${{ matrix.os }}
      target: ${{ matrix.target }}
      python-version: ${{ matrix.python-version }}
    name: Release (${{ matrix.os }})
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
        target: [x86_64]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    permissions:
      contents: read
      id-token: write
